ASSEMBLY = AssemblyInfo.cs
FILTER = *Filter.cs
#NAMER = ApiNamer.cs DocStudioNamer.cs
NAMER = ApiNamer.cs WhidbeyNamer.cs
VISITOR = ApiVisitor.cs

CCI = ..\CCI\System.Compiler.dll

all: Microsoft.Ddue.Tools.Reflection.dll

Microsoft.Ddue.Tools.Reflection.dll: $(ASSEMBLY) $(FILTER) $(NAMER) $(VISITOR) $(CCI)
	csc /t:library /out:Microsoft.Ddue.Tools.Reflection.dll $(ASSEMBLY) $(FILTER) $(NAMER) $(VISITOR) /r:$(CCI)
	copy Microsoft.Ddue.Tools.Reflection.dll ..\..\ProductionTools
