ALTER TABLE [dbo].[CryptoKey]
    ADD CONSTRAINT [PK_CryptoKeys] PRIMARY KEY CLUSTERED ([CryptoKeyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

